In [2]:
#task 1

In [7]:
import pandas as pd, scipy, numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler

ds = pd.read_excel("Job_Scheduling.xlsx")
x=ds.iloc[:,0:4].values #for input values
np.set_printoptions(precision=3)
y=ds.iloc[:,4].values #for output values

imp = SimpleImputer(missing_values=np.nan, strategy='mean')


X=imp.fit_transform(x)


# scaler=MinMaxScaler(feature_range=(0,1))
# X=scaler.fit_transform(X)

Y=y.reshape(-1,1)
Y=imp.fit_transform(Y)
Y=Y.reshape(-1)

print(X)
print(Y)

[[3.340e+02 1.790e+02 6.875e-01 1.000e+00]
 [2.340e+02 3.400e+02 7.800e-01 0.000e+00]
 [1.380e+02 1.430e+02 9.150e-01 1.000e+00]
 [4.630e+02 2.640e+02 4.803e-01 0.000e+00]
 [2.830e+02 2.160e+02 5.550e-01 0.000e+00]
 [8.800e+01 3.600e+01 6.625e-01 0.000e+00]
 [3.960e+02 1.280e+02 1.975e-01 1.000e+00]
 [4.700e+02 2.030e+02 9.875e-01 1.000e+00]
 [3.350e+02 2.710e+02 2.750e-02 0.000e+00]
 [2.720e+02 3.990e+02 2.150e-01 5.556e-01]
 [2.370e+02 1.929e+02 4.825e-01 1.000e+00]
 [3.180e+02 3.110e+02 5.675e-01 1.000e+00]
 [8.400e+01 1.110e+02 2.725e-01 1.000e+00]
 [3.110e+02 8.700e+01 4.803e-01 0.000e+00]
 [1.630e+02 1.030e+02 4.600e-01 0.000e+00]
 [4.530e+02 2.130e+02 7.750e-02 1.000e+00]
 [1.760e+02 2.510e+02 7.050e-01 0.000e+00]
 [4.490e+02 4.900e+01 2.550e-01 1.000e+00]
 [1.100e+01 1.680e+02 3.175e-01 1.000e+00]]
[4.    4.    4.    5.    6.    5.    4.167 4.    3.    3.    4.    1.
 2.    7.    5.    1.    6.    4.    7.   ]


In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(Y)

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.40)

In [10]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X, y)
#Predict Output
predicted= model.predict([[0,0.2,0.4,0.6]])
print ("Predicted Value:", predicted)
y_pred = model.predict(X_test)

Predicted Value: [3]


In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("\nClassification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[0 1 0 0 0]
 [0 4 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]]

Classification Report:
              precision    recall  f1-score   support

           2       0.00      0.00      0.00         1
           3       0.50      1.00      0.67         4
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1

    accuracy                           0.50         8
   macro avg       0.10      0.20      0.13         8
weighted avg       0.25      0.50      0.33         8

Accuracy: 0.5
